import { Box } from "@mui/system";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          mx={3}
          sx={{ px: { xs: 1, sm: 10, md: 15, lg: 32 }, my: { xs: 5, md: 10 } }}
        >
          <p>App Content</p>
        </Box>
      </main>
    </div>
  );
}
