import { Box } from "@mui/system";
import Head from "next/head";
import { TabInterface } from "../components/TabInterface";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lend3r</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box mx={3}>
          <TabInterface />
        </Box>
      </main>
    </div>
  );
}
